apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
namespace: test-bed # kpt-set: ${namespace}
resources:
- namespace.yaml
- cert.yaml
- deployment.yaml
- ingress.yaml
- svc.yaml
